ZeroK-RTS/Chobby

LuaMenu/configs/gameConfig/zk/helpSubmenuConfig.lua, LuaMenu/widgets/gui_settings_window.lua
=> Fixed some link and settings text for clarity and information

LuaMenu/configs/gameConfig/zk/defaultSettings/configversions.json, LuaMenu/configs/gameConfig/zk/settingsMenu.lua, LuaMenu/configs/springsettings/springsettings0.lua, LuaMenu/configs/springsettings/springsettings1.lua, LuaMenu/configs/springsettings/springsettings2.lua, LuaMenu/configs/springsettings/springsettings3.lua, LuaMenu/configs/springsettings/springsettings4.lua
=> Reduce FontSize to 18pt

LuaMenu/widgets/api_user_handler.lua
=> Chobby/#395 No more blurry flags

LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/CircuitAIEasy32/stable/config/circuit.json
Crippled Hard, capped mex at 30%, build delay 30s. See
http://zero-k.info/Forum/Post/176208#176208 for details.
=> New Easy CircuitAI config

campaign/sample/planets/planet29.lua
Fixed wincondition and made optional objectives a bit more achievable.
=> [Campaign] Fixes to FFA mission

campaign/sample/planets/planet14.lua, campaign/sample/planets/planet24.lua, campaign/sample/planets/planet25.lua, campaign/sample/planets/planet40.lua
Djinns are still uncooperative with respect to initial beacon commands.
=> Made corrections to mission 24 and added flavour to some planets.

LuaMenu/widgets/api_limit_fps.lua
Tested and seems to work.
Closes #287
=> Fix flicker

LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/CircuitAIBeginner/stable/config/circuit.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/CircuitAIBrutal/stable/config/circuit.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/CircuitAIEasy/stable/config/circuit.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/CircuitAIHard/stable/config/circuit.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/CircuitAINormal/stable/config/circuit.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/CircuitAINovice/stable/config/circuit.json, LuaMenu/configs/gameConfig/zk/gameUnitInformation.lua, campaign/sample/planetDocumentation.lua, campaign/sample/planets/planet1.lua, campaign/sample/planets/planet10.lua, campaign/sample/planets/planet11.lua, campaign/sample/planets/planet12.lua, campaign/sample/planets/planet15.lua, campaign/sample/planets/planet16.lua, campaign/sample/planets/planet19.lua, campaign/sample/planets/planet2.lua, campaign/sample/planets/planet3.lua, campaign/sample/planets/planet37.lua, campaign/sample/planets/planet4.lua, campaign/sample/planets/planet41.lua, campaign/sample/planets/planet42.lua, campaign/sample/planets/planet47.lua, campaign/sample/planets/planet5.lua, campaign/sample/planets/planet6.lua, campaign/sample/planets/planet9.lua, campaign/sample/planets/sample_planet.lua
See https://github.com/ZeroK-RTS/Zero-K/issues/2545
This PR does _not_ implement:
- Banshee -> Locust
- Krow -> Aurora
- Reaper -> Beast
- Amphfac -> Amphibious Base
- Cobra -> Axe
- Screamer -> Artemis
- DDM -> Desolator
- Annihilator -> Lucifer
- Puppy -> Bunny
=> Many unit renames.

LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/CircuitAIBrutal/stable/config/circuit.json
See https://github.com/ZeroK-RTS/Chobby/issues/353
=> Update by ScorchedEarther

LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/CircuitAIBrutal/stable/config/circuit.json
Brutal circuit config update 05-11-17
Makes use of new feature to  add "since" field to various unit.
Numerous changes to improve competitive performance.
=> Brutal circuit config update 05-11-17

README.md
This doesn't change much, but seems to result in a whole bunch of commits
=> make equivalent to upstream

campaign/sample/planets/planet21.lua
This is a bit of a shot in the dark.
=> Attempted tuning of mission 21 (dante), particularly chicken modoptions.

LuaMenu/widgets/chobby/core.lua, libs/chiliui/luamenu/chili/chili/handlers/fonthandler.lua
=> Fix invisible font bug

campaign/sample/planets/planet16.lua, campaign/sample/planets/planet19.lua, campaign/sample/planets/planet2.lua
Moved overdrive hint to mission 19.
=> Put a "don't make a second factory" hint in mission 2.

campaign/sample/planets/planet18.lua
1/2 terraform cost, added metal fabricator and fusion, replaced some amphs with subs.
=> Changes to mission 18 (terraform)

LuaMenu/configs/gameConfig/zk/ModOptions.lua
https://github.com/ZeroK-RTS/Zero-K/commit/3fc3d4d34c9004d45e67e1fecf6992b9a9ead401
=> Modoptions up to parity with ZK

campaign/sample/planets/planet33.lua
Mostly blind change but should be safe.
=> Replaced two solars in mission 33 with a fusion.

LuaMenu/widgets/gui_campaign_handler.lua
Reduces width of the 'Invite Friends' button and adds an add-to-party icon
=> Campaign - Invite Friends with Icon

LuaMenu/widgets/chobby/components/configuration.lua, LuaMenu/widgets/chobby/headers/exports.lua, LuaMenu/widgets/gui_chili_lobby.lua, LuaMenu/widgets/gui_settings_window.lua
Lets the user pick the locale for the luamenu and sets it when changed. Loads saved locale on start. 
Does not cause instantiated components to redraw with new texts because i have no idea how to do that.
=> Language selector

LuaMenu/widgets/gui_modoptions_panel.lua
Shows additional tooltips in the Mod Options menu
=> Mod Options : Add tooltip data for text and combo boxes

LuaMenu/widgets/chobby/i18n/chililobby.lua
Is there any reason why this does not start with an uppercase letter? It's been bugging me for a while now....
So this PR fixes that.
=> Uppercase the c in commanders

LuaMenu/widgets/chobby/components/console.lua
Small fix to address https://github.com/ZeroK-RTS/Chobby/issues/640 since it bugs me and should be relatively straightforward, I'll address the TODO if my changes look reasonable and useful
=> Display channel topic only once in the console

LuaMenu/widgets/api_featured_maps.lua, LuaMenu/widgets/gui_battle_room_window.lua, LuaMenu/widgets/gui_maplist_panel.lua
=> Display map dimensions / type in battle room.

LuaMenu/widgets/api_featured_maps.lua, LuaMenu/widgets/chobby/components/configuration.lua, LuaMenu/widgets/gui_maplist_panel.lua, libs/chiliui/chili/controls/control.lua, libs/chiliui/chili/controls/editbox.lua, libs/chiliui/chili/controls/object.lua, libs/chiliui/chili/controls/textbox.lua, libs/chiliui/chili/headers/skinutils.lua, libs/chiliui/chili/headers/util.lua
Reverts ZeroK-RTS/Chobby#795
Whoops. The wrapping text in the chat window is broken.
=> Revert "Improve performance of initial map list display"

LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/DevCircuitTest64/stable/config/behaviour.json
Added global per-UnitDef retreat multiplier. Because it's syntax change and not new tag all other difficulties should be updated with new syntax (or AI won't load).
Fixed idle factories that may happen in mid-game.
Fixed free-line check on group merge.
=> Update CircuitAI dll {1.2.2}

LuaMenu/configs/gameConfig/zk/settingsMenu.lua, LuaMenu/widgets/gui_settings_window.lua
Show the active GPU detected by spring in Graphics Settings. Adds a reusable label type for settings menus.
=> Active GPU in Graphics Settings

LuaMenu/configs/gameConfig/zk/mainConfig.lua, Sounds/lobbyMusic/licenses.txt
This PR adds 'Dreams of Cipher' as a track, adds license, and sets the track as default before resuming to classic tracks.
=> New lobby music

LuaMenu/configs/springsettings/springsettingsChanges.lua, LuaMenu/widgets/chobby/components/configuration.lua
rel: https://github.com/ZeroK-RTS/Zero-K/issues/5081
=> Add settings table for value minimal requirements; apply to atlas size
