libs/liblobby/lobby/interface_shared.lua, libs/liblobby/lobby/interface_zerok.lua
This list is rest by JoinChannelResponse so the server should either send JoinChannelResponse for #zk before it sends users or it should initially send the correct list in JoinChannelResponse for #zk.
=> #zk now acts as a list of everyone you can see on the ZKS.

LuaMenu/configs/gameConfig/zk/settingsMenu.lua
Sets both compatibility modes to ROAM=1 for the time being. ROAM=0's renderer seems to not be quite on par with ROAM=1, though it is faster, but it doesn't handle complex geometry (ex. Onyx Cauldron) that well yet. Fixes #102
=> ROAM Compatibility fix (for #102)

LuaMenu/configs/gameConfig/zk/settingsMenu.lua
New ROAM uses that value instead of GroundDetail.
=> Added GroundDetailBias adjustments to Chobby Terrain Detail settings

campaign/sample/planets/planet1.lua, campaign/sample/planets/planet2.lua, campaign/sample/planets/planet3.lua, campaign/sample/planets/planet5.lua
Mission 1: Warrior not unlocked, "Kill 10 Glaives" -> "Destroy all enemy mexes"
Mission 2: Warrior unlocked, Stardusts reduced in number and repositioned, one starts in LoS
Mission 3: Start with a con assisting factory, AI builds Leveller, AI does not build Dart
Mission 5: Removed most starting units, AI starts with more Stinger/Stardust, a Conjurer walks into LoS range of a few of them at the start
=> Changes to initial missions.

LuaMenu/widgets/api_download_handler.lua
fix #398
Tested locally, seems to work.
=> Prevent arithmetic error causing download handler to crash

LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/CircuitAIBrutal/stable/config/circuit.json
Updated config to use
"mobile": 0.35,  // initial modifier for power of attack group based on mobile enemy threat
"static": 0.075  // initial modifier for power of attack group based on static enemy threat
Applied the new "since" tag to stop circuit making certain units too early.
Now will use larger groups in reaction to enemy porc (previously did not scale up attack group size up unless players made mobile units.
Also includes various tweaks and improvements - better production curve in teamgames now (previously would overproduce caretaker on low metal). More accurate threat value for various units, such as scalpel. Better production response. Now builds more cons when it scouts a lot of enemy eco structures (interprets this scouting as "I have successfully attacked and now need to get …
=> Brutal Circuit Config update 14-11-17

campaign/sample/planets/planet34.lua, campaign/sample/planets/planet37.lua, campaign/sample/planets/planet50.lua, campaign/sample/planets/planet65.lua, campaign/sample/planets/planet70.lua, campaign/sample/planets/planet71.lua
- Servos from 37 to 71 and 34 to 70
- Battle drone from 65 to 37
- Nano from 50 to 34
These changes leave 50 (jumpfac) and 65 (detri) without modules. Jump module is intended to be added to 50 later.
=> Module unlock changes.

LuaMenu/configs/gameConfig/zk/ModOptions.lua, LuaMenu/widgets/gui_modoptions_panel.lua
* the Reset button now visually changes the controls as well.
Previously it failed to do this for modoptions whose applied value was the default, for default-true checkboxes, and for `disabledunits`.
* numericals with step 0.1 now have 1 digit of precision (previously 3)
* numericals not aligned to step are now rounded (previously floored)
=> Fix issues with the modoptions window

campaign/sample/planets/planet41.lua
Put a note about inefficiency instead
=> Blitz: remove EMP death mention

campaign/sample/planets/planet1.lua, campaign/sample/planets/planet10.lua, campaign/sample/planets/planet11.lua, campaign/sample/planets/planet12.lua, campaign/sample/planets/planet13.lua, campaign/sample/planets/planet15.lua, campaign/sample/planets/planet16.lua, campaign/sample/planets/planet18.lua, campaign/sample/planets/planet19.lua, campaign/sample/planets/planet2.lua, campaign/sample/planets/planet21.lua, campaign/sample/planets/planet22.lua, campaign/sample/planets/planet24.lua, campaign/sample/planets/planet25.lua, campaign/sample/planets/planet26.lua, campaign/sample/planets/planet27.lua, campaign/sample/planets/planet3.lua, campaign/sample/planets/planet30.lua, campaign/sample/planets/planet40.lua, campaign/sample/planets/planet47.lua, campaign/sample/planets/planet57.lua, campaign/sample/planets/planet58.lua, campaign/sample/planets/planet6.lua, campaign/sample/planets/planet63.lua, campaign/sample/planets/planet68.lua, campaign/sample/planets/planet7.lua, campaign/sample/planets/planet9.lua
On Easy and Normal, the player starts with a Reaver in Mission 3 (Imp/Picket).
Mission 6 (Knight) commander is now a Guardian com with two flamethrowers, so it cannot jump in holes.
Fixed Mission 47 (Flea/Widow) optional objective.
=> Campaign typo fixes and quality-of-life changes.

campaign/sample/planets/planet44.lua
=> Fix spawn config typo in mission 44

LuaMenu/widgets/gui_queue_status_panel.lua
The idea is to start playing instantly, which join doesn't directly suggest. (Even though the difference is minor)
=> Change MM "Click to Join" to "Click to Play now"

campaign/sample/planets/planet35.lua
There's a bonus objective to kill "the enemy commander" but there's an impostor that leaves people confused.
=> Likho mission: remove decoy comm

LuaMenu/widgets/gui_queue_status_panel.lua
Having to wait 30 seconds is annoying for both the player rejecting and the other players waiting for the accept/reject.
=> Allow rejecting MM games

LuaMenu/widgets/gui_queue_status_panel.lua
Reverts ZeroK-RTS/Chobby#651.
MM is testable. I tested reject on the test server, and the dev chobby rejected caused stable chobby to be banned.
=> Revert "Allow rejecting MM games"

LuaMenu/widgets/chobby/i18n/chililobby.lua, LuaMenu/widgets/gui_queue_status_panel.lua
=> Use a specialized message for Quickplay MM pop-ups

LuaMenu/widgets/gui_settings_window.lua
Bugfix that corrects Fullscreen issues on Windows 7 when paired a windowed lobby with a non-zero x and y coordinate set.
=> Set top left corner of fullscreen and manual fullscreen

LuaMenu/widgets/api_chili.lua
Improve lobby performance by comparing x,y against unscaled values and passing scaled dimensions to screen. Fixes #680
=> Lobby - Bugfix for High CPU at non-100% scale

LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/DevCircuitAIBrutal/stable/config/behaviour.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/DevCircuitAIBrutal/stable/config/build_chain.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/DevCircuitAIEasy/stable/config/behaviour.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/DevCircuitAIEasy/stable/config/build_chain.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/DevCircuitAIHard/stable/config/behaviour.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/DevCircuitAIHard/stable/config/build_chain.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/DevCircuitAINormal/stable/config/behaviour.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/DevCircuitAINormal/stable/config/build_chain.json, LuaMenu/configs/gameConfig/zk/defaultSettings/configversions.json
1. AI build antinukes in base, starting at around 15 minutes IF resources, available builders and battlefield situation allows.
1a. Hard and Brutal limit antinukes to 2
1b. Easy and Normal limit antinuke to 1
2. AI protects antinuke with a ring of lotus+faradays against paralyze (widow) attacks.
3. AI is much more likely to reinforces groups of turrets (of various kinds) with Faraday.
4. If completed everything that adds up to AI base and at late game stage, AI builds nuke silo in base (resources permitting) much earlier than more costly other superweapons.
5. AI consider having at least single heavy radar sensible thing past mid-game (can still have more, as before, but will aim to have at least one, in base, before commiting to long range projects). It considers such additional radar …
=> Improvements to CircuitAI - Brutal, Hard, Normal, and Easy.

LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/DevCircuitAIBrutal/stable/config/behaviour.json, LuaMenu/configs/gameConfig/zk/defaultSettings/AI/Skirmish/DevCircuitAIHard/stable/config/behaviour.json
AI builds one antinuke per AI player added to game, so it still ends with more than it (probably) needs, anyway.
=> Changed number of Antinukes for Hard and Brutal to 1 (from 2) 

LuaMenu/widgets/chobby/components/user_list_panel.lua
Offline users have a nil isAdmin, non-admins have a false isAdmin.
This caused comparisons to often enter the admin branch prematurely,
breaking alphabetical etc ordering.
`not not` rather than `not` for a simple inequality seems a little
superfluous, but consistency is important, and in any case, unrelated
nonfunctional changes can always be made in a separate commit.
=> Fix UserListPanel sorting

LuaMenu/widgets/chobby/components/user_list_panel.lua
This is generally more relevant while in the lobby, and helps make
clearer the:
> [liblobby] Warning: Duplicate user(...) added to channel (...)
problems, where it appears that an online and an offline user
share the same name. This issue is not fixed here.
This builds from #721
=> Userlistpanel: Show online users first

libs/liblobby/lobby/interface_zerok.lua
This allows banned players to create accounts and circumvent userid bans when they shouldn't be able to.
=> fix register not sending userid

LuaMenu/widgets/gui_campaign_handler.lua
Gates the story content of planets that are unable to be started by replacing their descriptions with placeholder text "This planet will need to be approached for further study." (enabling debug mode will bypass this change)
=> Limit campaign storyline to availability of missions

LuaMenu/widgets/api_limit_fps.lua, LuaMenu/widgets/chobby/components/configuration.lua, LuaMenu/widgets/gui_settings_window.lua
Adds a 'Minimize lobby updates' checkbox to the settings menu, which will allow Chobby to idle during inactivity, disabled by default (requires user testing as it may cause flicker on some systems), and adjusts the frame rate limiter
=> Chobby Flag to Minimize Draw Updates (CPU Usage)

LuaMenu/widgets/gui_campaign_handler.lua
Left pane uses 60% of available width for text and unlockables. All display elements become viewable down to 1366x768
Reduced font sizes for planet flavor text, reducing wrapping of early mission text (Folsom). Breakpoint adjustments to improve content visibility across resolutions
=> Campaign Planet View Layout Adjustments

campaign/sample/codex.lua
Replaced Anarchai scatterships by scattershapes, and one reference to starships by siege clusters. It was suggested that this would make them feel more alien if they don't have things as pedestrian as mere ships
Replaced an instance of 'Event' by 'event', as it is 'event' everywhere else. If 'Event' is better though, it could be changed everywhere instead.
Fixed the New Falsell hidden message
=> Campaign codex small edits

LuaMenu/widgets/gui_battle_room_window.lua, libs/liblobby/lobby/interface_zerok.lua
The poll candidates cannot directly override the map name since it is used
internally elsewhere (e.g. when looking up minimaps). Instead use a separate
displayName property populated on the server with dimensions.
=> Use map with dimensions in multi poll tooltip

LuaMenu/widgets/api_campaign_data.lua
If you had chosen any commander-modules that have prereqs, one of those would be replaced by empty-slot each time you loaded the campaign data.
=> Bugfix for the campaign commander silently losing modules on startup.

LuaMenu/widgets/api_featured_maps.lua, LuaMenu/widgets/gui_battle_room_window.lua, LuaMenu/widgets/gui_maplist_panel.lua
Thanks for fixing your own feedback already!
I set MapType on the map item, so that it's not necessary to double guard against whether the FeaturedMaps widget is available.
=> Address feedback on https://github.com/ZeroK-RTS/Chobby/pull/791

LuaMenu/widgets/api_featured_maps.lua, LuaMenu/widgets/chobby/components/configuration.lua, LuaMenu/widgets/gui_maplist_panel.lua, libs/chiliui/chili/controls/control.lua, libs/chiliui/chili/controls/editbox.lua, libs/chiliui/chili/controls/object.lua, libs/chiliui/chili/controls/textbox.lua, libs/chiliui/chili/headers/skinutils.lua, libs/chiliui/chili/headers/util.lua
I was surprised it took "so long" to show the map list so poked around trying to understand why.
The worst part by far is all the recursive copying that takes place during object init... I was able to make some very small improvements here.
Overall this sped up the time to initial show from 0.72s -> 0.45s. Many of the changes should be of general (small) benefit.
I'll add more comments inline or see the individual commits for details.
=> Improve performance of initial map list display

campaign/sample/planets/planet1.lua, campaign/sample/planets/planet2.lua, campaign/sample/planets/planet3.lua, campaign/sample/planets/planet5.lua
Planet 1: removed time constraints on mex/solars, win by X -> build 10 glaives
Planet 2: removed time constraint on Stardust objective
Planet 3: win by X -> build 4 more Imps
Planet 5: win by X -> kill enemy Radars, don't lose mex -> have 15 mex
=> Modified planet 1,2,3,5 optional objectives to reduce failability.

LuaMenu/configs/gameConfig/zk/defaultSettings/configversions.json
Disabled `isEnemyInArea` check - factories building non-stop (except air).
=> Update DevCircuitTest64 {1.2.6}

LuaMenu/widgets/api_ingame_interface.lua
Since people and maps can have `_` in names
=> Use `;` as the report string delimiter

LuaMenu/widgets/gui_tooltip.lua
Hi,
found a little issue while patching bar's chobby. Should be the same on ZK Chobby.
I have no ZK dev environment, can't test.
Hope it helps :)
Best regards
Fireball
=> FB_Tooltip_show_Moderator_Color

LuaMenu/widgets/gui_replay_handler.lua
Recoil versions past 2113 have a different filename structure of saved replays, breaking compatibility with current gui_replay_handler.lua in ZK Chobby. This PR replaces the string.sub based pattern with the string.match one from BAR Chobby. It parses the filenames of both older and newer replays.
This is a replay generated from a newer engine version that can be loaded for testing purposes: https://www.beyondallreason.info/replays?gameId=ead35d6547d4387665e51caef343a03f
Before:
After:
=> Chobby: Change replayTime to a pattern that is compatible with engine >2113.

LuaMenu/widgets/chobby/i18n/chililobby.lua, LuaMenu/widgets/gui_maplist_panel.lua, LuaMenu/widgets/gui_tooltip.lua
The good: Adds a higher res true aspect preview of the minimap when moused over a map in the selection menu. Text description is context sensitive to local map availability and changes status after map download is completed.
The so-so: Current set of minimaps is inconsistent in many aspects, some don't have water, some are screenshots, some only show diffuse tex. BAR makes better use of this by having a hand-crafted set of top-down screenshots for each map. Lots of work to do them all.
The bad: Setting an image for `fallbackFile` isn't working and I don't know why, it (the grey reload roundsquare) works in other places but maps with no valid minimap just have a white square in tooltip.
=> Add minimap preview tooltip and enable it in map browser.

LuaMenu/widgets/chobby/components/configuration.lua
For example the thumbnail and minimaps for [Fool's mate v0.6](https://zero-k.info/Maps/Detail/63354) are at
https://zero-k.info/Resources/Fool_s_mate_v0.6.thumbnail.jpg
https://zero-k.info/Resources/Fool_s_mate_v0.6.minimap.jpg
Not
https://zero-k.info/Resources/Fool's_mate_v0.6.thumbnail.jpg
https://zero-k.info/Resources/Fool's_mate_v0.6.minimap.jpg
See [PlasmaShared.Utils.EscapePath(this string path)](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/690f506c27fd8c12ae28ea9b28ecde16b67fa3b2/Shared/PlasmaShared/Utils.cs#L382-L392)
=> Fix thumbnail and minimap download for maps containing unusual chars

LuaMenu/widgets/gui_maplist_panel.lua
This is a bugfix for the following error: 
In the maplist gui panel, if enter is pressed while searching for a mapname that doesn't exist (example ASDFGH), this appears in log:
```[Chili] Error: in `Maplist Panel`:editbox3 : [string "LuaMenu/Widgets/gui_maplist_panel.lua"]:604: attempt to get length of field '?' (a nil value)
[t=00:01:34.036217][f=-000001] [Chili] Error: stacktrace:
[string "LuaMenu/Widgets/gui_maplist_panel.lua"]:604: in eventListener
[string "libs/chiliui/chili/controls/object.lua"]:728: in CallListeners
[string "libs/chiliui/chili/controls/object.lua"]:1074: in KeyPress
[string "libs/chiliui/chili/controls/editbox.lua"]:939: in KeyPress
... (6 calls)
[string "LuaHandler/Utilities/specialCallinHandlers.lua"]:132
(tail call): in [?]```
=> Fix length of field error in map search when no map is found

LuaMenu/widgets/gui_settings_window.lua
Disable an older "aggressive" screen resolution fix that was overwriting user-set screen parameters. Potential fix for #881
=> Screen resolution stability fixes

LuaMenu/widgets/chobby/components/friend_list_window.lua
It's incorrectly doing if not bla == "foo", that results in if (not bla) == "foo", that's always false.
=> Fix bad test at FriendListWindow:OnRemoveUser.

LuaMenu/widgets/zk_loopback.lua, libs/liblobby/lobby/interface_shared.lua, libs/spring-launcher/luaui/widgets/api_spring_launcher.lua
Cherry picked from https://github.com/Spring-Chobby/Chobby/pull/560, itself a backport of https://github.com/beyond-all-reason/BYAR-Chobby/pull/827
**note:**  untested here! the changes should be safe but always good someone tests before applying, otherwise check the code to see it's safe. (I think so but I might have overlooked smth, also I only tested on linux).
Best way to test is running without the launcher (I do it as documented [here](https://github.com/beyond-all-reason/Beyond-All-Reason/wiki/Testing-New-Engine-Releases-in-BAR#using-a-local-version-directly)), also can try with network disconnected.  Also check with the launcher ofc to see it still works under normal conditions.
Please reach back if you see any issues.
* Fixes crashing  (maybe on linux only) when launcher not …
=> Fix socket leaks and bad error condition checks.

LuaMenu/widgets/chobby/components/configuration.lua
Zoomers struggle with file extensions since modern Windows hides them by default.
Also `VFS.FileExists` already returns a bool so no need for that "x and true or false" idiom.
=> Look for `devmode.txt.txt` as well
